// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEN65UVJDkEjeiUS4qspxCbWkfyJ6YzdE',
    appId: '1:313398410895:web:a80f82c0664f93b9dd3afa',
    messagingSenderId: '313398410895',
    projectId: 'fir-conflutter',
    authDomain: 'fir-conflutter.firebaseapp.com',
    storageBucket: 'fir-conflutter.appspot.com',
    measurementId: 'G-GQLCKRH7M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2iybjgZW10GKyK6XJWUvGWyzGUiXNPLc',
    appId: '1:313398410895:android:cdc0dda33edc7873dd3afa',
    messagingSenderId: '313398410895',
    projectId: 'fir-conflutter',
    storageBucket: 'fir-conflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe5PZmr9ocre8QwgKIlxP9ubp-y60Avuo',
    appId: '1:313398410895:ios:b0e15e67326a1bb7dd3afa',
    messagingSenderId: '313398410895',
    projectId: 'fir-conflutter',
    storageBucket: 'fir-conflutter.appspot.com',
    iosBundleId: 'com.flutterconfirebase.sistemafacturacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe5PZmr9ocre8QwgKIlxP9ubp-y60Avuo',
    appId: '1:313398410895:ios:b0e15e67326a1bb7dd3afa',
    messagingSenderId: '313398410895',
    projectId: 'fir-conflutter',
    storageBucket: 'fir-conflutter.appspot.com',
    iosBundleId: 'com.flutterconfirebase.sistemafacturacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEN65UVJDkEjeiUS4qspxCbWkfyJ6YzdE',
    appId: '1:313398410895:web:634e1fb9c6616b55dd3afa',
    messagingSenderId: '313398410895',
    projectId: 'fir-conflutter',
    authDomain: 'fir-conflutter.firebaseapp.com',
    storageBucket: 'fir-conflutter.appspot.com',
    measurementId: 'G-C9MKXDZSLW',
  );
}
